aws/amazon-eks-pod-identity-webhook

- SELF_HOSTED_SETUP.md
N/A
Kubernetes doesn't set the key ID field until 1.16. Once 1.16 lands, this will need to be changed
CC @siwyd
> Removed key id from jwks JSON hack script 

- pkg/handler/handler.go
- pkg/handler/handler_test.go
Fixes https://github.com/aws/amazon-eks-pod-identity-webhook/issues/17
> Fix jsonpatch operation if no volumes are present

- README.md
The command to find the oidc endpoint is incorrect in the README.md doc today 
```
1. 
bash-5.0$ aws eks describe-cluster --name $CLUSTER_NAME --query cluster.tokenDiscoveryEndpoint
null
bash-5.0$
2. 
bash-5.0$ aws eks describe-cluster --name $CLUSTER_NAME --query cluster.identity.oidc
{
"issuer": "https://oidc.eks.us-west-2.amazonaws.com/id/ABCD"
}
bash-5.0$
```
> Making changes for finding the oidc discovery endpoint in README.md

- main.go
*Issue #, if available:* #15 
This makes two changes:
1. Enables the middleware on the /mutate endpoint.
2. Fixes the initial middleware setup that resulted in a recursive loop as there was no handler for `/` except the middleware itself.
> fix stack overflow and enable middleware

- README.md
- pkg/handler/handler.go
- pkg/handler/handler_test.go
**Issue #:** AWS Support Case ID `6708626561`
**Description of changes:**
If the pod is a windows container (identified by the `nodeSelector` `beta.kubernetes.io/os`), the path to the identity file is modified to be a valid windows path.
**Example:** `C:\var\run\secrets\eks.amazonaws.com\serviceaccount\token` is used instead of `/var/run/secrets/eks.amazonaws.com/serviceaccount/token`
> Ensure AWS_WEB_IDENTITY_TOKEN_FILE points to correct path on windows pod

- README.md
- main.go
- pkg/handler/handler.go
- pkg/handler/handler_test.go
Pods using IRSA should have information about what regions they are running in so that they can communicate with the correct AWS endpoints.
Update amazon-eks-pod-identity-webhook to set the AWS_DEFAULT_REGION environment variable into each mutated container if the value isn't set already.
> Inject AWS_DEFAULT_REGION in mutated pods

- SELF_HOSTED_SETUP.md
*Issue #, if available:* #11 
*Description of changes:* Revert change in #37 that caused a regression in the instructions for self-hosting.
> SELF_HOSTED_SETUP.md: use correct public key

- Makefile
Improve from just a hard sleep to a polling check for the existence of an approvable CSR.
Similar to #47, but potentially more robust.
While trying to set things up with this Makefile, we were running into issues where, for various reasons, the Pod wasn't coming up fast enough to have made the CSR within 1 second. This meant that we tried to approve the CSR and failed at it since it didn't exist yet. It also led to issues where it would mask a failure of the Pod to come up for reasons like the Image not being accessible, since the Makefile would "succeed". With this system, if the Pod never comes up, the CSR is never made, and the Makefile will stall indefinitely.
I'm not totally sure I like that as a failure model, but I also didn't want to write a massive shell script in here to handle …
> Update Makefile to poll for CSR creation

- pkg/handler/handler.go
fixed some lint warnings.
- k8s.io/api/core/v1.Volume composite literal uses unkeyed fields
- redundant type from array, slice, or map composite literal
> Fix some lint warnings

- Makefile
`make push` does not work with aws-cli v2 because `aws ecr get-login` command has been removed. This PR will replace the login command with `aws ecr get-login-password`. It is available in v1.17.10 or later.
> Update ecr login command for both aws-cli v1 and v2

- Makefile
This cert is tied to the deployment, and causes issues if you 
```
cluster-up
delete-config
cluster-up
```
resulting in loop of `kubectl certificate approve $$(kubectl get csr -o jsonpath='{.items[?(@.spec.username=="system:serviceaccount:default:pod-identity-webhook")].metadata.name}')`
N/A
Add delete of secret in Makefile
> Update Makefile to delete created tls cert

- Makefile
- README.md
- main.go
kubernetes secrets use file names `tls.key` for the key and `tls.crt` for the certificate; match them with our defaults.
---
> Default --tls-cert to tls.crt to match kubernetes secret TLS field

- ATTRIBUTIONS.txt
- Dockerfile
Add license attribution document to the docker container created via `make docker`.
> Add attribution document to container

- deploy/mutatingwebhook.yaml
fixes #46
Adds `sideEffects: None` to the `MutatingWebhookConfiguration` definition so that dry run operations will succeed.
> deploy: add sideEffects to webhook

- .github/workflows/container-image.yaml
Add a github workflow that triggers a new build of amazon-eks-pod-identity-webhook on each commit.
The new image is then pushed to dockerhub.
Tagged commits produce a tagged docker image, other commits produce a docker image tagged with a short commit hash.
Issue #5
> Add github worflow to automate docker image creation

- pkg/handler/handler.go
- pkg/handler/handler_test.go
Before, the updatePodSpec function would return immediately if it detected that the
aws-iam-token volume was already present.
This patch modifies the behavior so that the function continues to
inject environment variables and volume mounts as needed.
Specifically, the behavior of injecting env vars, volume mounts, and
volumes is now:
1. For each env var in "AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE,
AWS_REGION, AWS_DEFAULT_REGION", inject if not already present in
container spec
2. Inject volume mount if not already present in container spec
3. Inject volume if not already present in pod spec
Fixes https://github.com/aws/amazon-eks-pod-identity-webhook/issues/61
> patch pod spec even if it's already been patched

- README.md
*Issue #, if available:* https://github.com/aws/amazon-eks-pod-identity-webhook/pull/86
Document how non-root containers can access the token file.
> README: add documentation for running containers as non-root

- .gitignore
- Dockerfile
- Makefile
- README.md
- go.mod
- go.sum
- main.go
- pkg/annotations.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/fake.go
- pkg/handler/handler.go
- pkg/handler/handler_pod_test.go
- pkg/handler/handler_test.go
- pkg/handler/testdata/betaWindowsPodWithoutVolumes.pod.yaml
- pkg/handler/testdata/initPodNeedsRegion.pod.yaml
- pkg/handler/testdata/rawPodHasAll.pod.yaml
- pkg/handler/testdata/rawPodHasSTS.pod.yaml
- pkg/handler/testdata/rawPodHasVolumeMount.pod.yaml
- pkg/handler/testdata/rawPodNeedsRegion.pod.yaml
- pkg/handler/testdata/rawPodNeedsSTS.pod.yaml
- pkg/handler/testdata/rawPodNoSTSAnnotationOverride.pod.yaml
- pkg/handler/testdata/rawPodRegionPresent.pod.yaml
- pkg/handler/testdata/rawPodSkip.pod.yaml
- pkg/handler/testdata/rawPodWithInitContainer.pod.yaml
- pkg/handler/testdata/rawPodWithVolumes.pod.yaml
- pkg/handler/testdata/rawPodWithoutVolumes.pod.yaml
- pkg/handler/testdata/windowsPodWithoutVolumes.pod.yaml
N/A
The default for most AWS v1 SDKs is to use the global STS endpoint (`https://sts.amazonaws.com`, hosted in `us-east-1`) when talking to STS, resulting in a cross-region call for anything not in `us-east-1` just to get credentials. (some v2 SDKs such as [Java v2](https://github.com/aws/aws-sdk-java-v2/issues/1745) use regional). The way to force AWS SDKs to use the regional STS endpoint is to add the `AWS_STS_REGIONAL_ENDPOINTS` environment variable and set the value to `regional`. 
For applications running in Kubernetes pods using this webhook, this setting can now be automatically configured by adding the ServiceAccount annotation `eks.amazonaws.com/sts-regional-endpoints` with a value of `"true"`, or if operating this webhook on a …
> Added AWS_STS_REGIONAL_ENDPOINTS flag/annotation

- README.md
- main.go
- pkg/cache/cache.go
- pkg/cache/debug/debug.go
- pkg/cache/debug/debug_test.go
- pkg/cache/fake.go
- pkg/handler/handler.go
Added a debug endpoint to debug application state. Similar to the kubelet flag --enable-debugging-handlers.
Pre-1.16, audit logs do not have mutation decision annotated. If appropriate logging level is enabled, mutation decision logs could be of help for those clusters.
Issues such as https://github.com/aws/amazon-eks-pod-identity-webhook/issues/83 would be easier to debug
Open to suggestions/feedback on this.
> Add a debug handler to list cache contents and log mutation decision

- README.md
- main.go
- pkg/annotations.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/fake.go
- pkg/constants.go
- pkg/handler/handler.go
- pkg/handler/handler_pod_test.go
- pkg/handler/handler_test.go
- pkg/handler/testdata/rawPodHasAll.pod.yaml
- pkg/handler/testdata/rawPodHasTokenExpiration.pod.yaml
- pkg/handler/testdata/rawPodMinTokenExpiration.pod.yaml
- pkg/validation.go
Added annotation capability for both ServiceAccount and Pod to enable option to modify the expirationSeconds for the token, just like it is available as a flag to the binary. 
Note that the annotation in the pod would take precedence over the annotation in the service account to allow the ability to have certain pods where a customer wants to use a different expiration in seconds. Mentioned this distinction in the README as well.
> Add annotation option for token expiration

- main.go
- pkg/cert/request.go
89
- [Go 1.15 deprecated the use of the CommonName field](https://golang.org/doc/go1.15#commonname) as a HostName when no SANs are present.[Kubernetes v1.19](https://github.com/kubernetes/kubernetes/pull/93264) is now built with 1.15 and so has this deprecation in place
- Signer Name can not be empty. Consumers of client-go's certificate manager has to pass in a valid signer as this [PR](https://github.com/kubernetes/kubernetes/pull/88246/files) does on this [line](https://github.com/munnerz/kubernetes/blob/d5dae048983cd299cdce9d2703f564bf4bd246ee/pkg/kubelet/certificate/kubelet.go#L110) 
Without the signer name, CSRs were not admitted into the system with
```
I1230 01:57:37.015897       1 main.go:207] Listening on :443
E1230 …
```
> Add DNSName to SAN for go1.15 CN deprecation and add signer name to CSRs

- .github/workflows/test.yaml
- README.md
- go.mod
- main.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/fake.go
test more cases. https://github.com/aws/amazon-eks-pod-identity-webhook/pull/116#discussion_r636566019
Instead of calling addSA directly, use a fake client/informer. This is a closer approximation of reality, because we want to test that: given a serviceaccount already exists , and we start the controller, does it pick it up.
since this is a big refactor I also intend to test it end to end when I have time.
> Refactor service account cache to accept informer arg and unit test it 

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/handler/handler.go
While handling the infrastructure for a cluster, we need a way to know which clusters are using the webhook to drive changes that change default values through the infra.
> add metrics for knowing adoption

- main.go
- pkg/cache/cache.go
- pkg/handler/handler.go
- pkg/handler/handler_pod_test.go
first commit is the fix. spotted by  jyotimahapatra . Second commit is some refactoring that follows from the fix. basically it is unclear what parameters are coming from where, so the changes are to make the code clearer without changing behavior:
- Remove Expiration and RegionalSTSEndpoint from Modifier because they are
unused and redundant since serviceaccount cache already parses them.
- Refactor newPodUpdateSettings to parsePodAnnotations
- Rename updatePodSpec to getPodSpecPatch
- Fix changed being set false if the last container is skipped and no
other changes are made
I will test the changes on my EKS cluster
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> Fix serviceaccount regional sts annotation not taking effect unless flag is true

- README.md
- deploy/deployment-base.yaml
- deploy/mutatingwebhook.yaml
*Description of changes:* updates to
* deploy/deployment-base.yaml
- setting in-cluster=false
- update volumeMounts paths
- add cert-manager deployment
- cert-manager.io/v1 ClusterIssuer
- cert-manager.io/v1 Certificate
* deploy/mutatingwebhook.yaml
- add annotations to replace caBundle
> add cert manager deployment

- README.md
- main.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
This PR adds an option for the webhook to watch a configmap for additional SA to Role mappings. This is useful where there are tooling that creates IAM Roles and already know what SA should use them. In particular kOps already has this mapping. Adding the annotation to the SAs is then just additional manual work.
A few notes:
* There is a number of ways to watch a configmap. I opted for using another informer that is namespaced rather than e.g mounting it on disk and watching the file.
* Previously, all SAs were added to cache regardless of if they had the annotation. This made an empty SA override what was populated from the ConfigMap if the SA was created/changed after the CM was read. I changed this to only add to cache if the annotation is present. I believe …
> Add option to pass configmap with mapping between SA and IAM role

- pkg/handler/testdata/rawPodWithGRPC.pod.yaml
- pkg/handler/testdata/rawPodWithsecCompProfile.pod.yaml
- vendor/github.com/emicklei/go-restful/v3/log/log.go
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
Adding a test to ensure we don't break scenario in https://github.com/aws/amazon-eks-pod-identity-webhook/issues/165 and https://github.com/aws/amazon-eks-pod-identity-webhook/issues/168
PS: the last commit missed a file in vendor/ adding it here.
> add tests for grpc health probes and seccompProfile

- Makefile
It looks like when the webhook ca stuff was removed the mutatingwebhook.yaml was removed as well.
This commit simply adds the corresponding aply and delete for that manifest.
closes #176 
This commit simply adds the corresponding aply and delete for that manifest.
I have tested this by running cluster-up and cluster-down on my own clusters.
> fix: Reintroduce mutatingwebhook.yaml

- Dockerfile
- Makefile
*Issue #, if available:* N/A
Enable cross-compilation in Dockerfile. We need to add ARG TARGETOS TARGETARCH for them to be populated by buildx.
> Enable cross-compilation in Dockerfile

- Dockerfile
Use eks-distro go-runner as the base image instead of `scratch` so we can utilize go-runner to output stderr and stdout of the container to a file.
> Use eks-distro go-runner as the base image

- Dockerfile
*Issue #, if available: N/A
Upgrade Go compiler to version `1.21` and update base image (`eks/go-runner`) version
> Upgrade Go compiler to version 1.21 and update base image version

- main.go
- pkg/containercredentials/config.go
- pkg/containercredentials/config_test.go
- pkg/containercredentials/fake.go
- pkg/handler/handler.go
- pkg/handler/handler_pod_test.go
- pkg/handler/handler_test.go
- pkg/handler/testdata/containercredentials/rawPodNeedsAll.pod.yaml
- pkg/handler/testdata/containercredentials/rawPodSkip.pod.yaml
- pkg/handler/testdata/containercredentials/rawPodWithConflictingVolumeMount.pod.yaml
- pkg/handler/testdata/containercredentials/rawPodWithRoleArn.pod.yaml
- pkg/handler/testdata/containercredentials/rawPodWithVolume.pod.yaml
- pkg/handler/testdata/containercredentials/rawPodWithoutVolumes.pod.yaml
Update container credentials method to use a different mount path than the STS AssumeRoleWithWebIdentity method.  Prior this change, both methods will use the same mount path for the service account token.  However, this approach may cause confusions during migration from the AssumeRoleWithWebIdentity method to the Container credentials method.
Suppose user has the following AWS config file, which would signal SDK to use the AssumeRoleWithWebIdentity method.
```
[profile my_profile]
role_arn = arn:aws:iam::11111111:role/my-cool-role
web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
When the container credentials method is enabled for the service account, the audience of the token …
> Update container credentials method to use a different mount path

- pkg/handler/handler.go
- pkg/handler/middleware.go
Adds prometheus metric to emit number of pods using sts web identity or container credentials
> add metric to emit number of pods using sts web identity or container credentials

- .github/workflows/build.yaml
Don't attempt to push to dockerhub if the token or secret variable isn't set. 
> Don't push if there is no token or secret for dockerhub

- main.go
Currently the pod identity container wouldn't exit on SIGTERM because metricsServer is not handling the signal and would only exit on SIGKILL. Adding signal handling to the metric server also such that server is gracefully shutdown on SIGTERM
We can now see the graceful shutdown log after the change
```
I0221 21:37:52.906702      11 reflector.go:377] k8s.io/client-go/informers/factory.go:159: forcing resync
I0221 21:38:42.900211      11 file_watcher.go:91] context closed, stopping FileWatcher
I0221 21:38:42.900305      11 main.go:319] Graceflully closed
```
> gracefully terminate on SIGTERM

- go.mod
- go.sum
update kubernetes client version from 0.29.1 to 0.29.2
> update kubernetes client version

- deploy/mutatingwebhook.yaml
Adds a condition to the mutating webhook, preventing pods from being processed with a particular label.
See: https://github.com/aws/amazon-eks-pod-identity-webhook/issues/215
> feat: cannonical label for skipping pod identity webhook

- README.md
- main.go
Unify healthz and service port for both the traffic to be served on the same port. Prevents issues where pod is considered healthy but not serving any requests.
*Testing:*
```
❯ curl -k -i https://localhost:8443/healthz
HTTP/2 200
content-type: text/plain; charset=utf-8
content-length: 2
date: Tue, 02 Jul 2024 00:17:44 GMT
ok
```
> Unify healthcheck endpoint port with application port

- main.go
This PR removes the deprecated /healthz endpoint as part of unifying the healthcheck with the application port.
This change is a followup from an earlier PR: https://github.com/aws/amazon-eks-pod-identity-webhook/pull/229
> cleanup old healthz endpoint

- README.md
- main.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/debug/debug_test.go
- pkg/cache/fake.go
- pkg/handler/handler.go
- pkg/handler/handler_test.go
In #174 a race condition is mentioned, where the webhook tries to mutate a Pod having a service account reference which is not yet populated to the ServiceAccountCache. This results in the pod being not mutated. 
In our scenario this is a matter of a few milliseconds before the cache is properly populated. 
As an alternative to #178, this PR tries to fix this by waiting for a certain amount of time for proper ServiceAccountCache population and being notified upon population. Additionally, to wait only for SAs which aren't in the cache at all and not just missing a `RoleARN`, I had to restructure the return values of the `ServiceAccountCache` methods from multiple return values to structured data in order to transport the required information without adding additional two return values. …
> Fix race condition between service account availability and webhook invocation

- main.go
- pkg/cache/cache.go
- pkg/cache/debug/debug.go
- pkg/cache/fake.go
Makes 2 changes to help with debugging and local development:
- Inject the resync interval period
- Add routes for testing various scenarios, like empty cache, 500, deny, etc
> Add support for debugging

- pkg/handler/handler.go
Fixes a false-positive case where `pod_identity_webhook_missing_sa_count` increments when the SA is present, yet missing PI annotations. Since the SA is technically in the cache, the counter shouldn't increment.
We added this metric here: https://github.com/aws/amazon-eks-pod-identity-webhook/pull/246
We want this metric to only count cases where `pod.spec.serviceAccountName` references an SA that is missing in the cache. 
(also note that if `pod.spec.serviceAccountName` references a non-existent SA, PI Webhook will not receive the request because API server will refuse to create the pod)
> fix missingSACounter metric

- pkg/cache/cache.go
- pkg/cache/cache_test.go
#237
Support wildcards for namespace, meaning any ServiceAccount of a given name will be used regardless of what namespace it is in. Entries with a specific namespace defined takes precedence.
> Support ConfigMap cache entries with wildcard namespace

- main.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/notifications.go
- pkg/handler/handler.go
- vendor/k8s.io/client-go/util/retry/OWNERS
- vendor/k8s.io/client-go/util/retry/util.go
- vendor/modules.txt
Based on https://github.com/aws/amazon-eks-pod-identity-webhook/pull/242.
This PR enhances the implementation introduced in https://github.com/aws/amazon-eks-pod-identity-webhook/pull/236 by adding support to proactively fetch SA missed in cache from APIServer. 
- The grace period mechanism `service-account-lookup-grace-period` is still honored while the cache would initiate a GET request to APIServer in the meanwhile. If the SA is retrieved by APIServer request earlier than the grace period, the pod can be mutated earlier. Otherwise, cache would still wait till grace period ends and decide to not mutate the pod.
- The requests to the APIServer is deduplicated. All requests for the SA with same `namespace/name` will be deduped to a single …
> Fetch SA from apiserver

- .github/workflows/build.yaml
- README.md
https://github.com/aws/amazon-eks-pod-identity-webhook/issues/256
This change updates the actions pipeline to publish to the ECR public. Currently the repo alias is still being reviewed but we can start publishing to ECR before the custom alias is applied. Images can be viewed [here.](https://gallery.ecr.aws/eks/amazon-eks-pod-identity-webhook)
> Updating actions to publish to ecr public

- deploy/mutatingwebhook.yaml
Removed the namespace field because `MutatingWebhookConfiguration` is a cluster-scoped resource.
> Removed namespace as MutatingWebhookConfiguration is not namespaced

- main.go
- pkg/handler/shutdown.go
- pkg/handler/shutdown_test.go
Fixes https://github.com/aws/amazon-eks-pod-identity-webhook/issues/271, a race condition during shutdown that can lead to in-flight requests to the webhook being terminated abruptly on pod shutdown.
Previously, the metrics server was running on the main routine, while the webhook server was handled in a separate goroutine. This setup has been updated so that both the metrics server and the webhook server now run in dedicated goroutines, improving separation of concerns and shutdown coordination.
The `ShutdownFromContext()` function has been modified to return two channels:
- One signals when server shutdown is complete.
- The other reports any errors encountered during shutdown.
The main routine now listens on these channels to ensure that shutdown proceeds gracefully and completes …
> Implement graceful shutdown
